# Generated by Django 3.0.5 on 2020-04-19 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_remove_lot_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='expiration_time',
            new_name='expires_at',
        ),
    ]
