# Generated by Django 3.0.5 on 2020-04-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20200419_2233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
