# Generated by Django 3.0.5 on 2020-04-19 23:14

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_delete_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public identifier to be exposed in the API.', unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='bid',
            name='auction_bid_lot_id_a713cb_idx',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['lot', '-created_at'], name='auction_bid_lot_id_199ad5_idx'),
        ),
    ]
