# Generated by Django 3.0.5 on 2020-04-15 23:10

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='base_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='GBP', help_text='Starting price for the auction.', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='description',
            field=models.TextField(help_text='Item description.', null=True),
        ),
    ]
