# Generated by Django 3.0.5 on 2020-04-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20200415_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionbid',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
