# Generated by Django 3.0.5 on 2020-04-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20200418_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
